#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor HDMI-A-1 -d I II III IV V
bspc monitor HDMI-A-0 -d I

bspc config normal_border_color "#303446"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#ca9ee6"

# ОТСТУП ОКОН

bspc config border_width         3
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config pointer_modifier    super

bspc rule -a imv state=floating center=true
bspc rule -a mpv state=floating

xsettingsd &
pgrep -x sxhkd > /dev/null || sxhkd -f & #3апуск sxhkd
picom & # Запуск Picom
nitrogen --restore &
setxkbmap -model pc105 -layout us,ru -option grp:win_space_toggle & # Смена Раскладки
xsetroot -cursor_name left_ptr &
$HOME/.config/polybar/launch.sh &
xrandr --output HDMI-A-0 --mode 1920x1080 --rate 179.96 &
bspc config pointer_motion_interval 5ms
